### ISSUE TITLE
Ritchie doesn't find the $HOME PATH with space

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#438] opened 2020-08-14 21:02 UTC
**What happened**:

![Screen Shot 2020-08-14 at 18 00 45](https://user-images.githubusercontent.com/22433243/90292387-2d7ee280-de58-11ea-9780-a8b0c3a09520.png)

This may be related with this script:

```
bat-windows:
	echo '@ECHO OFF' > $(BAT)
	echo 'SET mypath=%~dp0' >> $(BAT)
	echo 'start /B /WAIT %mypath:~0,-1%/windows/main.exe' >> $(BAT)
```

Getting this **mypath** variable (would use "%~dp0" variable between " " resolve the problem ?)

**What you expected to happen**:

- I expected Ritchie to find the correct path

**How to reproduce it (as minimally and precisely as possible)**:

- Use Windows OS with your $Home path with a space.

ex: \Users\Dennis Ritchie\

**Anything else we need to know?**:

- You rock !

**Environment**:
- Ritchie version (use `rit --version`): 2.0.3
- Operating System: Window OS
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by lucasdittrichzup** [comment] 2020-09-18 15:23
After analyzing the request, we found that the cause of the problem lies in the formula scripts, **but specifically in that part**:

```sh
# build.bat

echo SET mypath=%%~dp0 >> %BAT_FILE%
echo start /B /WAIT %%mypath:~0,-1%%/windows/main.exe >> %BAT_FILE%
```

In the tests we performed, for the binary to run successfully for **"composite users"** _(eg Lucas Dittrich)_ on **Windows**, the code above should be:

```sh
echo SET mypath=%%~dp0 >> %BAT_FILE%  # Remove that line
echo start /B /WAIT windows/main.exe >> %BAT_FILE% # Removed part: '%%mypath:~0,-1%%/'
```

So, we are closing this activity and we will open one in the formula repository for proper adjustment.

**Closed by lucasdittrichzup** 2020-09-18 15:23 UTC
Labels: :beetle: bug
