### ISSUE TITLE
[BUG] Using rit build formula appends to application.bat instead of replacing

### ISSUE THREAD

**Issue by Fryuni** [ZupIT/ritchie-cli#238] opened 2020-07-02 19:15 UTC
**What happened**:
Buildin a formula with `rit build formula` creates appends the command to `application.bat` instead of regenerating it:
```
python main.py
python main.py
python main.py
python main.py
```

**What you expected to happen**:
The `application.bat` file should container only one command.

**How to reproduce it (as minimally and precisely as possible)**:
Create a new formula and run `rit build formula` on it twice.

**Environment**:
- Ritchie version: 1.0.0-beta.17 (single)
- Operating System: 
  ```
  Operating System: Pop!_OS 20.04 LTS
            Kernel: Linux 5.4.0-7634-generic
      Architecture: x86-64
  ```

**Comment by viniciusramosdefaria** [comment] 2020-07-16 13:36
The team is working on a new way of creating formulas. This happened because there was a `>` instead of a `>>` inside the Makefile.

**Comment by brunasilvazup** [comment] 2020-08-07 17:51
Hello,

When analyzing your issue in the new version 2.0.2, it's was not possible to reproduce the error.

I believe has been corrected.

I will close this issue, but if identify the error again in the latest stable version, please open a new issue by informing us.

Thank you for your contribution.

**Closed by brunasilvazup** 2020-08-07 17:51 UTC
Labels: bug
